name: FongMi TV Build

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  build:
    name: Build TV APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant gradlew permission
        run: chmod +x gradlew

      - name: Build TV Release APK
        run: |
          ./gradlew :app:assembleTvRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FongMi-TV-APK
          path: |
            app/build/outputs/apk/tv/release/*.apk
